/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_suiyi_jnidemo_NativeLib */

#ifndef _Included_com_suiyi_jnidemo_NativeLib
#define _Included_com_suiyi_jnidemo_NativeLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_suiyi_jnidemo_NativeLib
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_suiyi_jnidemo_NativeLib_printHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
